FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY equipment /equipment
COPY config.ini /equipment/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /equipment
USER appuser

WORKDIR /equipment
CMD ["python", "equipment.py", "config.ini"]

EXPOSE 6004
