FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY crypto /crypto
COPY config.ini /crypto/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /crypto
USER appuser

WORKDIR /crypto
CMD ["python", "crypto.py", "config.ini"]

EXPOSE 6007