FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY mixer /mixer
COPY config.ini /mixer/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /mixer
USER appuser

WORKDIR /mixer
CMD ["python", "mixer.py", "config.ini"]

