FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY bre /bre
COPY config.ini /bre/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /bre
USER appuser

WORKDIR /bre
CMD ["python", "bre.py", "config.ini"]
