FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY reporter /reporter
COPY config.ini /reporter/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /reporter
USER appuser

WORKDIR /reporter
CMD ["python", "reporter.py", "config.ini"]
