FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY storage /storage
COPY config.ini /storage/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /storage
USER appuser

WORKDIR /storage
CMD ["python", "storage.py", "config.ini"]
